### ISSUE TITLE
Question: Replacing MOVE statement does not work as separate rule?

### ISSUE THREAD

**Issue by m-badura** [SAP/abap-cleaner#120]
The rule _Replace obsolete MOVE ... TO ... with =_ (1) seems to not cover all cases, when used separately from _Unchain into multiple statements_ (2) and _Simplify a chain with one element_ (3).

Rule (1) will clean this code:
`MOVE: 1 to integer_1, 2 TO integer_2.`

This code will be cleaned only when rule (2) was selected too:
`MOVE: 1 to integer_3.`

This code will be cleaned only when rule (3) was selected too:
`MOVE 1 TO: integer_4, integer_5.`

Since this behavior seems very unintuitive, maybe it could be changed? And if not, at least documented by rule (1)?

**Comment by jmgrassau** [comment]
Hi m-badura, 

you're right, this indeed didn't work as intended! Actually, the option …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/94ed72ae-7879-4cad-8c3f-b8b6561fded7)

… was introduced at some point in order to make this cleanup rule independent of the other two rules, but not all cases were covered then. Now this should be fixed in the next release:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/a3763c6a-a25c-4c91-ba1d-8a212c0702bd)

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi m-badura, 

thanks again for opening this issue! This should now be fixed with version 1.6.0, which was just released. 

Kind regards,
Jörg-Michael

**Comment by m-badura** [comment]
Hi Jörg-Michael,
sorry for getting back on this to You, but I'm afraid the rule is still not 100 % accurate...

Here are examples:

`MOVE 1: TO integer.
MOVE 1 TO integer:.
MOVE 1: TO integer_1, integer_2.
MOVE 1 TO integer:,.
MOVE EXACT: 1 to integer.
MOVE EXACT 1: TO integer.
MOVE EXACT 1 TO integer:.
MOVE EXACT: 1 TO integer_1, 2 TO integer_2.
MOVE EXACT 1: TO integer_1, TO integer_2.
MOVE EXACT 1 TO integer:,.
MOVE object_1: ?TO object_2.
MOVE object_1 ?TO object_2:.
MOVE object_1: ?TO object_2, ?TO object_3
MOVE object_1 ?TO object_2:,.
`

**Comment by jmgrassau** [comment]
Hi m-badura, 

thanks for stress-testing this rule :-)

Modifying your examples a bit, so it's easier to see what happens (and fixing two issues in the third and penultimate line):

```ABAP
MOVE 1: TO integer.
MOVE 2 TO integer:.
MOVE 3: TO integer_1, TO integer_2.
MOVE 4 TO integer:,.
MOVE EXACT: 5 to integer.
MOVE EXACT 6: TO integer.
MOVE EXACT 7 TO integer:.
MOVE EXACT: 8 TO integer_1, 9 TO integer_2.
MOVE EXACT 10: TO integer_1, TO integer_2.
MOVE EXACT 11 TO integer:,.
MOVE object_a: ?TO object_1.
MOVE object_b ?TO object_1:.
MOVE object_c: ?TO object_1, ?TO object_2.
MOVE object_d ?TO object_1:,.
```

At least when activating "Unchain into multiple statements" and "Simplify a chain with one element", the result looks good to me:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/b30c367c-d8fd-49fd-9451-54dd599e33b6)

But you're right, the new option within "Replace obsolete MOVE ... TO with =" doesn't get any of those. Will look into it! 

Or maybe the solution should rather be to offer an additional option within "Unchain into multiple statements" with which obsolete commands like ADD, MOVE, TRANSLATE can be unchained, even if you don't want to unchain everything else? Then the dedicated "Replace obsolete …" rules wouldn't need to care about chains anymore. 

Kind regards,
Jörg-Michael

**Comment by m-badura** [comment]
> thanks for stress-testing this rule :-)

You're welcome! :)
But thanks for providing this tool, constant improving it and the communication with us, users, here on GitHub.


> Modifying your examples a bit (...)

I will not work nights, I will not work nights, ... ;)


> At least when activating "Unchain into multiple statements" and "Simplify a chain with one element", the result looks good to me:

Yes, of course! But then it should be documented by the _Replace obsolete..._ rule.


> Or maybe the solution should rather be to offer an additional option within "Unchain into multiple statements" with which obsolete commands like ADD, MOVE, TRANSLATE can be unchained, even if you don't want to unchain everything else? Then the dedicated "Replace obsolete …" rules wouldn't need to care about chains anymore.

You've got me for it!

**Comment by jmgrassau** [comment]
Hi m-badura, 

with version 1.9.0, which was just released, all your examples should now correctly be replaced! 

Pondering this for a while, I did however find that "decentral" options are better. Therefore, in 8 rules in the "COMMANDS" group (marked in yellow here) …

![image](https://github.com/SAP/abap-cleaner/assets/79639298/c52622e6-ffdf-44cd-8ad4-e72a694aa74c)

… you will now find new options like:

![image](https://github.com/SAP/abap-cleaner/assets/79639298/c2836c7e-a10e-4a4b-b287-6e74e818d58f)
![image](https://github.com/SAP/abap-cleaner/assets/79639298/38700fb0-72a8-4809-9875-8b32eed94f93)
![image](https://github.com/SAP/abap-cleaner/assets/79639298/0b846477-ac57-4b06-b8ed-3b0fb853e521)
![image](https://github.com/SAP/abap-cleaner/assets/79639298/19a45a62-de38-4c47-b9f5-c492a7e54aac)
![image](https://github.com/SAP/abap-cleaner/assets/79639298/eebbfa7d-d6da-4656-a5fb-ebd3dfa81e5e)

These options will, in a pre-processing step, first unchain all these obsolete statements (or remove the colon from a "chain of one"), so the replacement then works on all of them. That means, however, that unchaining will include cases in which some (or even all) statements can not be replaced: 

![image](https://github.com/SAP/abap-cleaner/assets/79639298/2fe4fb79-2569-448f-b7c2-1e20573b8afa)

![image](https://github.com/SAP/abap-cleaner/assets/79639298/2dbb0d8b-84c1-43fe-8738-7fd9f8105fb3)

But I think replacing old or even obsolete syntax in as many cases of as possible is a higher gain than keeping such chains. 

Thanks again for opening this issue and testing this rule so thoroughly! 

Kind regards,
Jörg-Michael
