### ISSUE TITLE
New ABAP cleaner release not found by Eclipse 

### ISSUE THREAD

**Issue by OS-Baumgart** [SAP/abap-cleaner#305]
Hello,

I am using "Eclipse IDE for Java Developers (includes Incubating components)" Version: 2024-03 (4.31.0) Build id: 20240307-1437 and unfortunately the ABAP cleaner release 1.16.1 is not found when I try to update it via _Help->Check for Updates_.
![grafik](https://github.com/SAP/abap-cleaner/assets/150137982/d279ef40-3f8d-4758-a5fa-64651b4f628c)
![grafik](https://github.com/SAP/abap-cleaner/assets/150137982/84883880-ba2a-4a4e-9e03-ab295bb29dce)

I already edited the `eclipse.ini` as mentioned here https://github.com/SAP/abap-cleaner/blob/main/docs/installation-issues.md#known-installation-issues but this has no effect.

What do I have to do to be able to update to the latest ABAP cleaner release (currently 1.16.1)?

Kind Regards,
Kai

**Comment by jmgrassau** [comment]
Hi Kai, 

that's odd – generally, ABAP cleaner 1.16.1 seems to be found, at least I have not yet heard of another case where it wasn't. I'll have to ask a colleague about it. 

Kind regards,
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Kai, 

I just released version 1.16.2, maybe you could try again whether this is now found. 

Kind regards,
Jörg-Michael

**Comment by OS-Baumgart** [comment]
Hi  Jörg-Michael,

unfortunately, the new version is still not found. 

Kind Regards,
Kai
